# Project: include_pro
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = main.o math_ops.o
LINKOBJ  = main.o math_ops.o
LIBS     = -L"E:/Program Files/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib32" -static-libgcc -m32 -g3
INCS     = -I"E:/Program Files/Embarcadero/Dev-Cpp/TDM-GCC-64/include" -I"E:/Program Files/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"E:/Program Files/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"E:/Program Files/Embarcadero/Dev-Cpp/TDM-GCC-64/include" -I"E:/Program Files/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"E:/Program Files/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"E:/Program Files/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = include_pro.exe
CXXFLAGS = $(CXXINCS) -m32 -g3 -fexec-charset=GBK -finput-charset=UTF-8
CFLAGS   = $(INCS) -m32 -g3 -fexec-charset=GBK -finput-charset=UTF-8
DEL      = E:\Program Files\Embarcadero\Dev-Cpp\devcpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

math_ops.o: math_ops.c
	$(CC) -c math_ops.c -o math_ops.o $(CFLAGS)
